apiVersion: v1
kind: Service
metadata:
  name: ms-producto-api-service
  namespace: ms-producto-namespace
  labels:
    app: ms-producto-api
spec:
  type: ClusterIP
  selector:
    app: ms-producto-api
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
